const IDENTIFIER = "/products/";

export const SET_PRODUCTS_REQUEST = `${IDENTIFIER}SET_PRODUCTS_REQUEST`;
export const SET_PRODUCTS_SUCCESS = `${IDENTIFIER}SET_PRODUCTS_SUCCESS`;
export const SET_PRODUCTS_FAILED = `${IDENTIFIER}SET_PRODUCTS_FAILED`;

export const DELETE_PRODUCT_REQUEST = `${IDENTIFIER}DELETE_PRODUCT_REQUEST`;
export const DELETE_PRODUCT_FAILED = `${IDENTIFIER}DELETE_PRODUCT_FAILED`;

export const ADD_PRODUCT_REQUEST = `${IDENTIFIER}ADD_PRODUCT_REQUEST`;
export const ADD_PRODUCT_FAILED = `${IDENTIFIER}ADD_PRODUCT_FAILED`;
